### ISSUE TITLE
Default and Pro classes are re-added upon server restart

### ISSUE THREAD

**Issue by luisc99** [MC-Minigames/Conquer#1]
Hey,

First off, Id like to say thanks for an amazing plugin. It's very nice to use, and customisable. I really enjoy using it ;)

I have found on issue though. It seems that upon a server restart, the "Default" and "Pro" classes are re-added to the config file if the user has removed them. I've taken a look at your code to try and see if I can fix it via a PR, although I am unsure of how you use your dependencies to create and manage configs. From what I can tell though, you are using .copyDefaults(true); in your custom IClassesConfig without actually checking if the file exists already, possibly causing the plugin to add them to the file. Again, I'm not sure if this is the issue, as I am unable to get this plugin imported into Eclipse correctly, and am unable to try changing this to see if it works.

Thanks :smiley:
Luis

**Comment by instance01** [comment]
Hey,

when using MinigamesLib 1.5 (or just latest dev builds) it'll not load kits which have "enabled: false" added, so that might fix the issue. :)

**Comment by luisc99** [comment]
I'll give it a go, thanks ;)

EDIT: I might just be a derp, but only MinigamesLib v1.4 is available over at your drone.io page. Am I missing where 1.5 is found?

**Comment by instance01** [comment]
Oh I call the current version 1.5 because 1.4 is already released and I'm working towards 1.5. Just use the build from drone :P

**Comment by luisc99** [comment]
Ah, solved it. Thanks for your help ;D

Also, I've noticed that scores remain on the scoreboard from one game to another, as seen here. Not sure how easy this'd be to solve.
![d73a3328-2b09-11e4-8756-0a54faa932d1](https://cloud.githubusercontent.com/assets/3613896/4021839/d73a3328-2b09-11e4-8756-0a54faa932d1.jpg)

**Comment by instance01** [comment]
Oh that's interesting, thanks for the report!

**Comment by instance01** [comment]
This commit should fix the scoreboard issue: e28919c5da1926949f607e2b4f7d64e936bfc1b9
